favicon:
enable_auth_headers: true
debug: true
plugins: 
  - name: ChartJS
    enabled: true
  - name: SabnzbdTraffic
    enabled: true
    baseurl: "http://192.168.178.81:8081"
    apikey: '8a0f8b8ae12b6d8eea08e43b4215550f'
theme:
  colors:
    background: '#191919'
    backgroundmenu: '#111827'
    textcolormenu: '#83848f'
    titlecolor: '#d7dadc'
    boxbackgroundcolor: '#111827'
    boxbordercolor: '#4b5563'
    boxheading: '#d7dadc'
    boxcontent: '#d7dadc'
    groupelement: '#1a253c'
  templates:
    head:
    header_header:
    header_logo:
    header_mobile-menu:
    navigation_nav-container:
    navigation_nav-item:
    container:
    groups_group:
    groups_group-item:
  classes-override:
    header_header:
    header_logo:
    header_mobile-menu:
    navigation_nav-container:
    navigation_nav-item:
    container:
    groups_group:
    groups_group-item:
  classes-additional:
    header_header:
    header_logo:
    header_mobile-menu:
    navigation_nav-container:
    navigation_nav-item:
    container:
    groups_group:
    groups_group-item:
header:
 logo:
   logo_override: false
   title: "Dashboard"
 mobilemenu:
 navigation:
  items:
    - url: 'https://mail.galli.li'
      text: 'Mail'
      groups:
        - mail
      design:
        class:
          - bg-opaci
    - url: 'https://account.galli.li/change_password/'
      text: 'Change Password'
    - url: 'https://auth.galli.li/logout/'
      text: 'Logout'
groups:
  - name: Media
    groups:
      - media
    items:
      - url: 'https://jellyfin.galli.li'
        text: 'Jellyfin'
        logo_file: jellyfin.svg
      - url: 'https://sonarr.galli.li/'
        text: 'Sonarr'
        logo_file: sonarr.svg
        groups:
          - admins
      - url: 'https://radarr.galli.li/'
        text: 'Radarr'
        logo_file: radarr.svg
        groups:
          - admins
      - url: 'https://bazarr.galli.li/'
        text: 'Bazarr'
        logo_file: bazarr.png
        groups:
          - admins
      - url: 'https://sonarr.galli.li/jackett/UI/'
        text: 'Jackett'
        logo_file: jackett.png
        groups:
          - admins
  - name: Misc
    items:
      - url: 'https://bitwarden.galli.li'
        text: 'Vaultwarden'
        logo_file: bitwarden-icon.svg
      - url: 'https://nextcloud.galli.li'
        text: 'Nextcloud'
        groups:
          - 'cloud'
        logo_file: nextcloud.png
  - name: Downloaders
    groups:
      - admins
    items:
      - url: 'https://transmission.galli.li'
        text: 'Transmission'
        logo_file: transmission.svg
      - url: 'https://nzb.galli.li/'
        text: 'Sabnzbd'
        logo_file: sabnzbd.webp
      - url: 'https://jdownloader.galli.li/'
        text: 'JDownloader'
        logo_file: jdownloader.png
  - name: Development
    groups:
      - developer
    items:
      - url: 'https://ide.galli.li/'
        text: 'Theia'
        logo_file: theia.svg
        groups:
          - admins
      - url: 'https://nzb.galli.li/'
        text: 'Huginn'
        logo_file: huginn.png
  - name: Communication
    items:
      - url: 'https://mail.galli.li/'
        text: 'Webmail'
        groups:
          - mail
      - url: 'https://mail.galli.li/admin'
        text: 'Mail Administration'
        logo_file: 'mailu.png'
        groups:
          - mail
      - url: 'https://element.galli.li/'
        text: 'Matrix Element'
        logo_file: 'element.svg'
        groups:
          - chat
      - url: 'https://dimension.galli.li/'
        text: 'Matrix Dimension'
        logo_file: 'dimension.png'
        groups:
          - chat
  - name: Managment
    groups:
      - admins
    items:
      - url: 'http://galli.li:81'
        text: 'Nginx Proxy Manager'
        logo_file: nginxproxymanager.png
      - url: 'https://portainer.galli.li/'
        text: 'Portainer'
        logo_file: portainer.png
      - url: 'https://dozzle.galli.li/'
        text: 'Dozzle'
        logo_file: dozzle.svg
      - url: 'https://mail.galli.li/admin'
        text: 'Mail Administration'
        logo_file: 'mailu.png'
      - url: 'https://matrix.galli.li/synapse-admin/#/login'
        text: 'Synapse Admin'
        logo_file: 'matrix-favicon.png'
      - url: 'https://cockpit.galli.li'
        text: 'Cockpit'
        logo_file: cockpit.png

  - name: Sabnzb
    groups:
      - admins
    plugin: SabnzbdTraffic
